### PR TITLE
Added function for finding N:N relationship name.

### PR DESCRIPTION
**Pull request by DynamicsNinja**
Removed the unnecessary parameter for a relationship schema name and added a function that finds the right N:N relationship.

### CODE REVIEW

**Comment by MscrmTools** [comment]
Thank you for this improvement.
I’m just wondering what happens if two or more non relationship exist between the same entities?

**Comment by DynamicsNinja** [comment]
Good point about the parameter thing. I didn't think about the situation where you can have more than one N:N relationship.

**Comment by MscrmTools** [comment]
In my example, that could be primary tags, secondary tags.
Do you update your PR or do I merge it and adapt it?

**Comment by DynamicsNinja** [comment]
I can do it, no problem.

**Comment by MscrmTools** [comment]
Thanks!

**Comment by DynamicsNinja** [comment]
I returned the relationshipSchemaName parameter back and set it as optional. 

If you set something in the parameter control will not search for N:Ns automatically and will try to associate/disassociate records against that schema name defined in the parameter, if it fails it will warn you about the wrong schema name defined. 

Otherwise, if schema name parameter is empty then it will search for the schema name in the metadata, if it doesn't find anything it will pop error message that there is no N:N relationship found.

**Comment by MscrmTools** [comment]
Seems fine! I will merge PR tomorrow

**Pull request merged**
